---
title: "RMarkdown Resource List"
author: "Anthony Chau"
date: "9/1/2020"
output: md_document
---

## RMarkdown Resources
- [RMarkdown Docs by RStudio](https://rmarkdown.rstudio.com/index.html)
  - Focus on high level overview of RMarkdown
  - Good for getting the big picture of what's possible with RMarkdown
- [RMarkdown Guide by Xie, Allaire, Grolemund](https://bookdown.org/yihui/rmarkdown/)
  - More of a canonical reference of everything possible with RMarkdown
- [Meta RMarkdown blog post by Thomas Mock](https://themockup.blog/posts/2020-07-25-meta-rmarkdown/)
  - Discusses use cases and workflows with RMarkdown
- [RMarkdown Driven Development blog post by Emily Riederer](https://emilyriederer.netlify.app/post/rmarkdown-driven-development/)
  - Discusses different patterns for structuring a RMarkdown document
- [How I Teach RMarkdown blog post by Allison Hill](https://alison.rbind.io/post/2020-05-28-how-i-teach-r-markdown/)
  - Discusses pedagogical strategies to teach RMarkdown
  - I definitely used ideas from this post!
- [Good Enough Practices in Scientific Computing](https://arxiv.org/abs/1609.00037)
  - Paper discussing tools and techniques that could be adopted by researchers to support scientific and reproducible research
- [Interactive Markdown Tutorial](https://commonmark.org/help/tutorial/)


